name: General Bug Report
description: File a general bug report
title: "Bug: "
labels: ["triage"]
assignees:
  - refringe
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out a bug report!
  - type: input
    id: discord-username
    attributes:
      label: Discord Username
      description: If we need more information, can we contact you on the SPT discord? What's your username?
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: SPT Version
      description: What version of SPT are you running?
      options:
        - 3.2.3 (latest)
        - 3.2.2
        - 3.2.1
        - 3.2.0
        - 3.1.1
        - 3.1.0
    validations:
      required: true
  - type: input
    id: server-log
    attributes:
      label: "Server Log"
      description: "[Upload your server log](https://codepaste.sp-tarkov.com/) and paste the URL here. Set expire to 'never'. Log is found here `/user/logs/server-yyyy-mm-dd-xx.log`."
      placeholder: "https://codepaste.sp-tarkov.com/?6611c5a1892e7de6#C8pJnqG9m9nU6ZS4rKozFRj5ryp7ofP2nvgMQNR2zQnq"
    validations:
      required: true
  - type: input
    id: client-log
    attributes:
      label: "Client Log"
      description: "[Upload your Client log](https://codepaste.sp-tarkov.com/) and paste the URL here. Set expire to 'never'. Log is found here `/Logs/log_<date>_<version>/<date>_<version> traces.log`."
      placeholder: "https://codepaste.sp-tarkov.com/?6611c5a1892e7de6#C8pJnqG9m9nU6ZS4rKozFRj5ryp7ofP2nvgMQNR2zQnq"
    validations:
      required: true
  - type: input
    id: profile
    attributes:
      label: "Profile"
      description: "[Upload your profile](https://codepaste.sp-tarkov.com/) and paste the URL here. Set expire to 'never'. Log is found here `/user/profiles/xxxxxxxxxxxx.json`."
      placeholder: "https://codepaste.sp-tarkov.com/?6611c5a1892e7de6#C8pJnqG9m9nU6ZS4rKozFRj5ryp7ofP2nvgMQNR2zQnq"
    validations:
      required: true
  - type: checkboxes
    id: tested-alone
    attributes:
      label: "Many issues are caused by mod compatibility issues. A simple way to tell whether this is a compatibility issue, or a core mod issue is to remove all other mods and see if the problem remains."
      options:
        - label: "I have experienced this issue when no other mods have been installed."
